linters-settings:
  gofumpt:
    simplify: true

  misspell:
    locale: US

  staticcheck:
    checks: ['all', '-ST1005', '-ST1000', '-SA4000', '-SA9004', '-SA1019', '-SA1008', '-U1000', '-ST1016']

linters:
  disable-all: true
  enable:
    - durationcheck
    - gocritic
    - gofumpt
    - goimports
    - gomodguard
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - usetesting
    - forcetypeassert
    - whitespace

issues:
  exclude-use-default: false
  max-issues-per-linter: 100
  max-same-issues: 100
  exclude:
    - "empty-block:"
    - "unused-parameter:"
    - "dot-imports:"
    - should have a package comment
    - error strings should not be capitalized or end with punctuation or a newline
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - forcetypeassert
