// --------  DO NOT EDIT --------
// This file is autogenerated by genversion.go during the release process.

package main

const minioVersion = "Sat, 19 Sep 2015 06:15:16 GMT"
const minioReleaseTag = "RELEASE.Sat-19-Sep-2015-06-15-16-GMT"
