# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  build:
    context: ../../.
    dockerfile: Dockerfile
  command: server --console-address ":9001" http:///data{1...8}
  expose:
    - "9000"
    - "9001"
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5
  depends_on:
    - etcd-server

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000 but they are also mapped to 9011..9014.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    ports:
      - "9011:9000"
    environment:
      MINIO_PUBLIC_IPS: 172.0.1.0
      MINIO_CI_CD: 1
      MINIO_ETCD_ENDPOINTS: http://etcd-server:2379
      MINIO_ETCD_COREDNS_PATH: /skydns
      MINIO_DOMAIN: local
    networks:
      default:
        ipv4_address: 172.0.1.0

  minio2:
    <<: *minio-common
    hostname: minio2
    ports:
      - "9012:9000"
    environment:
      MINIO_PUBLIC_IPS: 172.0.2.0
      MINIO_CI_CD: 1
      MINIO_ETCD_ENDPOINTS: http://etcd-server:2379
      MINIO_ETCD_COREDNS_PATH: /skydns
      MINIO_DOMAIN: local
    networks:
      default:
        ipv4_address: 172.0.2.0

  minio3:
    <<: *minio-common
    hostname: minio3
    ports:
      - "9013:9000"
    environment:
      MINIO_PUBLIC_IPS: 172.0.3.0
      MINIO_CI_CD: 1
      MINIO_ETCD_ENDPOINTS: http://etcd-server:2379
      MINIO_ETCD_COREDNS_PATH: /skydns
      MINIO_DOMAIN: local
    networks:
      default:
        ipv4_address: 172.0.3.0

  minio4:
    <<: *minio-common
    hostname: minio4
    ports:
      - "9014:9000"
    environment:
      MINIO_PUBLIC_IPS: 172.0.4.0
      MINIO_CI_CD: 1
      MINIO_ETCD_ENDPOINTS: http://etcd-server:2379
      MINIO_ETCD_COREDNS_PATH: /skydns
      MINIO_DOMAIN: local
    networks:
      default:
        ipv4_address: 172.0.4.0


  etcd-server:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd-server
    hostname: etcd-server
    ports:
      - "2379:2379"
    command: >
      /usr/local/bin/etcd
      --name etcd0
      --listen-client-urls http://0.0.0.0:2379
      --advertise-client-urls http://0.0.0.0:2379

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.0.0/16