blank_issues_enabled: false
contact_links:
  - name: MinIO Community Support
    url: https://slack.min.io
    about: Community support via Slack - for questions and discussions
  - name: MinIO Enterprise Support (SUBNET)
    url: https://min.io/pricing
    about: Enterprise support with SLA - for production deployments and feature requests
