{
 "title": "MinIO Node Dashboard",
 "description": "MinIO Nodes Grafana Dashboard - https://min.io/",
 "tags": [ "minio" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "scrape_jobs", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Drives",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(minio_node_drive_total{job=~\"$scrape_jobs\"})"
    }
   ]
  },
  {
   "title": "Total Online/Offline Drives",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_node_drive_online_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "."
    },
    {
     "expr": "max(minio_node_drive_offline_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "Drive Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "minio_node_drive_total_bytes{job=~\"$scrape_jobs\"}",
     "legendFormat": "Total [{{server}}:{{drive}}]"
    },
    {
     "expr": "minio_node_drive_used_bytes{job=~\"$scrape_jobs\"}",
     "legendFormat": "Used [{{server}}:{{drive}}]"
    },
    {
     "expr": "minio_node_drive_free_bytes{job=~\"$scrape_jobs\"}",
     "legendFormat": "Free [{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "Free Inodes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_drive_free_inodes{job=~\"$scrape_jobs\"}",
     "legendFormat": "[{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "Drive Latency (micro sec)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_drive_latency_us{job=~\"$scrape_jobs\"}",
     "legendFormat": "[{{server}}:{{drive}}:{{api}}]"
    }
   ]
  },
  {
   "title": "Drive Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_drive_errors_availability{job=~\"$scrape_jobs\"}",
     "legendFormat": "[{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "Drive Timeout Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_drive_errors_timeout{job=~\"$scrape_jobs\"}",
     "legendFormat": "[{{server}}:{{drive}}]"
    }
   ]
  },
  {
   "title": "IO Operations Waiting",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minio_node_drive_io_waiting{job=~\"$scrape_jobs\"}",
     "legendFormat": "[{{server}}:{{drive}}]"
    }
   ]
  }
 ]
}