// Code generated by "stringer -type=decomMetric -trimprefix=decomMetric erasure-server-pool-decom.go"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[decomMetricDecommissionBucket-0]
	_ = x[decomMetricDecommissionObject-1]
	_ = x[decomMetricDecommissionRemoveObject-2]
}

const _decomMetric_name = "DecommissionBucketDecommissionObjectDecommissionRemoveObject"

var _decomMetric_index = [...]uint8{0, 18, 36, 60}

func (i decomMetric) String() string {
	if i >= decomMetric(len(_decomMetric_index)-1) {
		return "decomMetric(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _decomMetric_name[_decomMetric_index[i]:_decomMetric_index[i+1]]
}
