// Copyright (c) 2015-2021 MinIO, Inc.
//
// This file is part of MinIO Object Storage stack
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by "stringer -type=osMetric -trimprefix=osMetric os-instrumented.go"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[osMetricRemoveAll-0]
	_ = x[osMetricMkdirAll-1]
	_ = x[osMetricRename-2]
	_ = x[osMetricOpenFile-3]
	_ = x[osMetricOpen-4]
	_ = x[osMetricOpenFileDirectIO-5]
	_ = x[osMetricLstat-6]
	_ = x[osMetricRemove-7]
	_ = x[osMetricStat-8]
	_ = x[osMetricAccess-9]
	_ = x[osMetricLast-10]
}

const _osMetric_name = "RemoveAllMkdirAllRenameOpenFileOpenOpenFileDirectIOLstatRemoveStatAccessLast"

var _osMetric_index = [...]uint8{0, 9, 17, 23, 31, 35, 51, 56, 62, 66, 72, 76}

func (i osMetric) String() string {
	if i >= osMetric(len(_osMetric_index)-1) {
		return "osMetric(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _osMetric_name[_osMetric_index[i]:_osMetric_index[i+1]]
}
