// Code generated by "stringer -type=osMetric -trimprefix=osMetric os-instrumented.go"; DO NOT EDIT.

package cmd

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[osMetricRemoveAll-0]
	_ = x[osMetricMkdirAll-1]
	_ = x[osMetricMkdir-2]
	_ = x[osMetricRename-3]
	_ = x[osMetricOpenFile-4]
	_ = x[osMetricOpen-5]
	_ = x[osMetricOpenFileDirectIO-6]
	_ = x[osMetricLstat-7]
	_ = x[osMetricRemove-8]
	_ = x[osMetricStat-9]
	_ = x[osMetricAccess-10]
	_ = x[osMetricCreate-11]
	_ = x[osMetricReadDirent-12]
	_ = x[osMetricFdatasync-13]
	_ = x[osMetricSync-14]
	_ = x[osMetricLast-15]
}

const _osMetric_name = "RemoveAllMkdirAllMkdirRenameOpenFileOpenOpenFileDirectIOLstatRemoveStatAccessCreateReadDirentFdatasyncSyncLast"

var _osMetric_index = [...]uint8{0, 9, 17, 22, 28, 36, 40, 56, 61, 67, 71, 77, 83, 93, 102, 106, 110}

func (i osMetric) String() string {
	if i >= osMetric(len(_osMetric_index)-1) {
		return "osMetric(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _osMetric_name[_osMetric_index[i]:_osMetric_index[i+1]]
}
